name: Pelican site CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pulsar17/gh-pages-pelican-action@0.2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PELICAN_THEME_FOLDER: apricot
        GH_PAGES_CNAME: pulsar17.me
